#ifndef _IDCARD_ERROR_H_
#define _IDCARD_ERROR_H_
//////////////////////////////////////////////////////////////////////////
#pragma once
//////////////////////////////////////////////////////////////////////////
#define IDCARD_ERROR_SUCCESS						0
#define IDCARD_ERROR_FAILURE						1
#define IDCARD_ERROR_NULL_POINTER					2
#define IDCARD_ERROR_NULL_FUNCTION					3
#define IDCARD_ERROR_NULL_INSTANCE					4
#define IDCARD_ERROR_MEMORY_ALLOCATE				5
#define IDCARD_ERROR_GET_APP_PATH					6
#define IDCARD_ERROR_PATH_ADD_BACKSLASH				7
#define IDCARD_ERROR_PATH_SET_ENVIRONMENT			8
#define IDCARD_ERROR_XML_LOAD_FAILURE				9
#define IDCARD_ERROR_XML_FIND_ELEMENT				10
#define IDCARD_ERROR_XML_FIND_ATTRIBUTE				11
#define IDCARD_ERROR_PATH_COMBINE_FAILURE			12
#define IDCARD_ERROR_MODULE_LOAD_FAILURE			13
#define IDCARD_ERROR_LOG_INIT_FAILURE				14
#define IDCARD_ERROR_CONFIG_INIT_FAILURE			15
#define IDCARD_ERROR_READ_INFO_FAILURE				16
#define IDCARD_ERROR_READ_PEOPLE_NAME_FAILURE		17
#define IDCARD_ERROR_READ_PEOPLE_SEX_FAILURE		18
#define IDCARD_ERROR_READ_PEOPLE_NATION_FAILURE		19
#define IDCARD_ERROR_READ_PEOPLE_BIRTHDAY_FAILURE	20
#define IDCARD_ERROR_READ_PEOPLE_ADDRESS_FAILURE	21
#define IDCARD_ERROR_READ_PEOPLE_ID_CODE_FAILURE	22
#define IDCARD_ERROR_READ_SIGN_DEPARTMENT_FAILURE	23
#define IDCARD_ERROR_READ_VALID_START_DATE_FAILURE	24
#define IDCARD_ERROR_READ_VALID_END_DATE_FAILURE	25
#define IDCARD_ERROR_READ_BITMAP_DATA_FAILURE		26
#define IDCARD_ERROR_FILE_CREATE_FAILURE			27
#define IDCARD_ERROR_FILE_WRITE_FAILURE				28
#define IDCARD_ERROR_PROCESS_CREATE_FAILURE			29
#define IDCARD_ERROR_NETWORK_INIT_FAILURE			30
#define IDCARD_ERROR_NETWORK_UNREACHABLE			31
#define IDCARD_ERROR_STRING_CONVERT_FAILURE			32
#define IDCARD_ERROR_JSON_CONVERT_FAILURE			33
#define IDCARD_ERROR_CREATE_PIPE_FAILURE			34
#define IDCARD_ERROR_READ_PIPE_FAILURE				35
#define IDCARD_ERROR_CREATE_PROCESS_FAILURE			36
#define IDCARD_ERROR_WAIT_THREAD_FAILURE			37
#define IDCARD_ERROR_WAIT_PROCESS_FAILURE			38
#define IDCARD_ERROR_GET_STD_HANDLE_FAILURE			39
#define IDCARD_ERROR_SET_STD_HANDLE_FAILURE			40
#define IDCARD_ERROR_EXECUTE_CURL_FAILURE			41
#define IDCARD_ERROR_NULL_PORT						42
#define IDCARD_ERROR_GET_REQUEST_FILENAME_FAILURE	43
#define IDCARD_ERROR_CREATE_REQUEST_FILE_FAILURE	44
#define IDCARD_ERROR_WRITE_REQUEST_FILE_FAILURE		45
#define IDCARD_ERROR_GET_RESPONSE_FILENAME_FAILURE	46
#define IDCARD_ERROR_GET_APP_CURL_PATH				47

#endif _IDCARD_ERROR_H_